#!/system/bin/sh
#
# Created by Calkulin and modded by misfit for 3d

READ_AHEAD_KB="512"

if [ -e /sys/devices/virtual/bdi/179:0/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:0/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi

if [ -e /sys/devices/virtual/bdi/179:64/read_ahead_kb ]; then
    echo $READ_AHEAD_KB > /sys/devices/virtual/bdi/179:64/read_ahead_kb
    echo "SD card read ahead kb SET to $READ_AHEAD_KB"
fi
