#!/system/bin/sh
# ===========================================================================
#  Run this section on every boot.
# ===========================================================================

if $TEST -d $CONTACT_PIC_DIR ; then
  $CHMOD 666 $CONTACT_PIC_DIR/*
fi
